PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= qsort
SRC_CXX		= main.cpp

CXXFLAGS	= -O0 -fno-inline-small-functions -fno-inline -fno-optimize-sibling-calls

#LIBS     += -ldl

include $(L4DIR)/mk/prog.mk
